# 以已有的 TensorFlow 镜像为基础
FROM nvcr.io/nvidia/tensorflow:24.02-tf2-py3

# 安装你需要的 Python 包
RUN pip install --no-cache-dir \
    numpy \
    matplotlib \
    pandas \
    scikit-learn \
    tqdm \
    ncps
